config/routes.rb
Reason::Application.routes.draw do
  resources :causes

  root :to => 'Causes#random'
  match 'random' => 'Causes#random', :as => 'random_cause'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/cause.rb
class Cause < ActiveRecord::Base
  attr_accessible :approved, :author, :content, :country, :day, :month,:holiday
  
  validates :holiday, inclusion: { in: %w(Birthday Religion National Other) }
  validates :content, presence: true, uniqueness: true
  validates :day, numericality: {
    only_integer: true,
    less_than_or_equal_to: 31
  }
  validates :month, numericality: {
    only_integer: true,
    less_than_or_equal_to: 12
  }

  before_save :set_prove

  def set_prove
		self.approved = false if approved.nil?
    true
  end

  def self.find_random
    causes = Cause.where('(day = ? AND month = ?) OR (day IS ?)', Time.now.day, Time.now.month, nil)
    causes.offset(rand(causes.count)).first || Cause.offset(rand(Cause.count)).first 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def index
  	
  end
end

app/controllers/causes_controller.rb
class CausesController < ApplicationController
  # GET /causes
  # GET /causes.json
  def index
    @causes = Cause.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @causes }
    end
  end

  # GET /causes/1
  # GET /causes/1.json
  def show
    @cause = Cause.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cause }
    end
  end

  # GET /causes/new
  # GET /causes/new.json
  def new
    @cause = Cause.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cause }
    end
  end

  # GET /causes/1/edit
  def edit
    @cause = Cause.find(params[:id])
  end

  # POST /causes
  # POST /causes.json
  def create
    @cause = Cause.new(params[:cause])

    respond_to do |format|
      if @cause.save
        format.html { redirect_to @cause, notice: 'Cause was successfully created.' }
        format.json { render json: @cause, status: :created, location: @cause }
      else
        format.html { render action: "new" }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /causes/1
  # PUT /causes/1.json
  def update
    @cause = Cause.find(params[:id])

    respond_to do |format|
      if @cause.update_attributes(params[:cause])
        format.html { redirect_to @cause, notice: 'Cause was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cause.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /causes/1
  # DELETE /causes/1.json
  def destroy
    @cause = Cause.find(params[:id])
    @cause.destroy

    respond_to do |format|
      format.html { redirect_to causes_url }
      format.json { head :no_content }
    end
  end

  def random
    @cause = Cause.find_random

    logger.debug @cause

    respond_to do |format|
      format.html
      format.json { render json: @cause }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/causes_helper.rb
module CausesHelper
end

app/views/causes/_form.html.erb
<%= form_for(@cause) do |f| %>
  <% if @cause.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cause.errors.count, "error") %> prohibited this cause from being saved:</h2>

      <ul>
      <% @cause.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :day %><br />
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :month %><br />
    <%= f.text_field :month %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :holiday %><br />
    <%= f.select( :holiday, 
      options_for_select([
        ['Other', 'Other'],
        ['Religion', 'Religion'],
        ['Birthday', 'Birthday'],
        ['National', 'National'],
      ]))%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/causes/edit.html.erb
<h1>Editing cause</h1>

<%= render 'form' %>

<%= link_to 'Show', @cause %> |
<%= link_to 'Back', causes_path %>

app/views/causes/index.html.erb
<h1>Listing causes</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Author</th>
    <th>Day</th>
    <th>Country</th>
    <th>Holiday</th>
    <th>Approved</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @causes.each do |cause| %>
  <tr>
    <td><%= cause.content %></td>
    <td><%= cause.author %></td>
    <td><%= cause.day %>-<%= cause.month %></td>
    <td><%= cause.country %></td>
    <td><%= cause.holiday %></td>
    <td><%= cause.approved %></td>
    <td><%= link_to 'Show', cause %></td>
    <td><%= link_to 'Edit', edit_cause_path(cause) %></td>
    <td><%= link_to 'Destroy', cause, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cause', new_cause_path %>

app/views/causes/new.html.erb
<h1>New cause</h1>

<%= render 'form' %>

<%= link_to 'Back', causes_path %>

app/views/causes/random.html.erb
<p id="notice"><%= notice %></p>

<h2>Let drink for...</h2>

<h1 class="reason">
  <%= @cause.content %>
</h1>

<p class="author">
  <b>Author:</b>
  <%= @cause.author %>
</p>

<p>
	<%= link_to 'Get new reason', random_cause_path, :class => 'get_new' %>
	<span class="loading">Loading</span>
</p>

app/views/causes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @cause.content %>
</p>

<p>
  <b>Author:</b>
  <%= @cause.author %>
</p>

<p>
  <b>Day:</b>
  <%= @cause.day %>
  <%= @cause.month %>
</p>

<p>
  <b>Country:</b>
  <%= @cause.country %>
</p>

<p>
  <b>Holiday:</b>
  <%= @cause.holiday %>
</p>

<p>
  <b>Approved:</b>
  <%= @cause.approved %>
</p>


<%= link_to 'Edit', edit_cause_path(@cause) %> |
<%= link_to 'Back', causes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reason</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", 'jquery.min' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>